# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

bioc_packages:
				- graph

branches:
    only:
        - master
matrix:
    include:
        - os: linux
          r: release
        - os: linux
          r: oldrel 
        - os: linux
          r: devel
        - os: osx
          r: release
        - os: osx
          brew_packages: libgit2
          r: oldrel

